trigger:
- manual

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadPipelineArtifact@2
  inputs:
    patterns: '**/*.exe,**/*.dll,**/*.pdb'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: $(AppName)
    publishLocation: 'Container'
    TargetPath: $(Build.ArtifactStagingDirectory)
    continueOnError: true

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode Connection'
    veracodeAppProfile: '$(AppName)'
    version: '$(AppName)_$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    sandboxName: '$(sandboxName)'
    createSandBox: true
    optargs: '-deleteincompletescan 1'
    failBuildIfUploadAndScanBuildStepFails: true
    importResults: true
    maximumWaitTime: '30'
