trigger:
- manual

pool:
  vmImage: 'windows-latest'

variables:
  - group: credentials
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: DownloadPipelineArtifact@2
  inputs:
    patterns: '**/*.exe,**/*.dll,**/*.pdb'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: $(AppName)
    publishLocation: 'Container'
    TargetPath: $(Build.ArtifactStagingDirectory)
    continueOnError: true

- task: Veracode@3
  displayName: Veracode Upload & Scan
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode Connection'
    veracodeAppProfile: '$(AppName)'
    version: '$(AppName)_$(build.buildNumber)'
    filepath: '$(Build.ArtifactStagingDirectory)'
    sandboxName: 'GitDemo'
    createSandBox: true
    failBuildIfUploadAndScanBuildStepFails: true
    importResults: true
    maximumWaitTime: '60'